{% set name = "openconnect" %}
{% set version = "9.01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # OpenConnect source. Favor https source over ftp so as to let conda-forge bot pick up updates.
  - url: https://www.infradead.org/openconnect/download/openconnect-{{ version }}.tar.gz
    sha256: b3d7faf830e9793299d6a41e81d84cd4a3e2789c148c9e598e4585010090e4c7

  # OpenConnect requires a configuration script to run.
  # It is downloaded from a separate repo.
  # See https://www.infradead.org/openconnect/vpnc-script.html
  - git_url: https://gitlab.com/openconnect/vpnc-scripts.git
    git_rev: e52f8e66
    folder: vpnc-scripts

build:
  number: 5
  skip: true  # [win]
  missing_dso_whitelist:
    - '/System/Library/Frameworks/PCSC.framework/**'  # [osx]
  skip_compile_pyc:
    - "*.py"  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - pkg-config
    - make
    - gnuconfig  # [unix]
    - gettext
  host:
    - gettext
    - gnutls >=3.6.13
    - libxml2
    - stoken
    - zlib
    - libiconv
    - lz4-c
    - krb5
    - nettle
    - p11-kit
  run:
    - gettext
    - gnutls
    - libxml2
    - stoken
    - zlib
    - libiconv
    - lz4-c
    - krb5

test:
  commands:
    - ${PREFIX}/bin/openconnect --version
    - test -f ${PREFIX}/etc/openconnect/vpnc-script

about:
  home: https://www.infradead.org/openconnect
  license: LGPL-2.1-only
  license_family: LGPL
  license_file:
    - COPYING.LGPL
    - vpnc-scripts/COPYING
  summary: 'OpenConnect is an SSL VPN client'
  description: |
    OpenConnect is an SSL VPN client initially created to support Cisco's AnyConnect SSL VPN.
    It has since been ported to support the Juniper SSL VPN (which is now known as
    Pulse Connect Secure), and the Palo Alto Networks GlobalProtect SSL VPN.

    An openconnect VPN server (ocserv), which implements an improved version of the Cisco AnyConnect
    protocol, has also been written.

extra:
  recipe-maintainers:
    - stuarteberg
    - leofang
